"""Tests for triage/commenter.py — comment text building."""

from __future__ import annotations

import pytest

from cnv_bug_triage.triage.checker import (
    BackportAnalysis,
    BackportRecommendation,
    DuplicateCandidate,
    FieldCheck,
    TriageResult,
    TriageSuggestion,
)
from cnv_bug_triage.triage.commenter import build_comment_text
from tests.conftest import make_bug


class TestBuildCommentText:
    def test_header_present(self):
        result = TriageResult(
            bug=make_bug(),
            checks=[FieldCheck("priority", False, "Undefined", "missing")],
        )
        text = build_comment_text(result, run_id="abc123")
        assert "[Bug Triage Agent]" in text
        assert "abc123" in text

    def test_missing_fields_listed(self):
        result = TriageResult(
            bug=make_bug(),
            checks=[
                FieldCheck("assignee", False, "(unassigned)", "No assignee"),
                FieldCheck("priority", False, "Undefined", "Priority is Undefined"),
            ],
        )
        text = build_comment_text(result)
        assert "Assignee" in text
        assert "(unassigned)" in text
        assert "Priority" in text
        assert "Undefined" in text

    def test_suggestions_included(self):
        result = TriageResult(
            bug=make_bug(),
            checks=[FieldCheck("priority", False, "Undefined", "missing")],
            suggestions=[
                TriageSuggestion("priority", "Major", "Major", "It affects migration"),
            ],
        )
        text = build_comment_text(result)
        assert "Major" in text
        assert "It affects migration" in text

    def test_no_suggestion_shows_fallback(self):
        result = TriageResult(
            bug=make_bug(),
            checks=[FieldCheck("assignee", False, "(unassigned)", "missing")],
        )
        text = build_comment_text(result)
        assert "no suggestion available" in text

    def test_backport_section(self):
        result = TriageResult(
            bug=make_bug(fix_versions=["CNV v4.22.0"]),
            checks=[FieldCheck("priority", True, "Major", "")],
            backport=BackportAnalysis(
                needs_backport=True,
                recommendations=[
                    BackportRecommendation("4.21", "release-4.21", "must", "Critical bug"),
                    BackportRecommendation("4.20", "release-4.20", "should", "Low risk"),
                ],
                overall_reasoning="Backport to all supported",
            ),
        )
        text = build_comment_text(result)
        assert "Backport" in text
        assert "4.21" in text
        assert "release-4.21" in text
        assert "MUST" in text
        assert "4.20" in text
        assert "SHOULD" in text
        assert "Backport to all supported" in text

    def test_duplicates_section(self):
        result = TriageResult(
            bug=make_bug(),
            checks=[FieldCheck("priority", False, "Undefined", "missing")],
            duplicates=[
                DuplicateCandidate("CNV-999", "Similar bug", 0.85, "Same stack trace"),
            ],
        )
        text = build_comment_text(result)
        assert "Potential duplicates" in text
        assert "CNV-999" in text
        assert "85%" in text
        assert "Same stack trace" in text

    def test_footer(self):
        result = TriageResult(
            bug=make_bug(),
            checks=[FieldCheck("priority", False, "Undefined", "missing")],
        )
        text = build_comment_text(result, run_id="xyz")
        assert "Generated by cnv-bug-triage" in text
        assert "run: xyz" in text

    def test_fully_triaged_no_backport_minimal(self):
        result = TriageResult(
            bug=make_bug(),
            checks=[FieldCheck("priority", True, "Major", "")],
        )
        text = build_comment_text(result)
        assert "missing" not in text.lower()
        assert "Generated by cnv-bug-triage" in text

    def test_backport_with_suggested_fix_version(self):
        result = TriageResult(
            bug=make_bug(fix_versions=[]),
            checks=[FieldCheck("fix_version", False, "(none)", "missing")],
            suggestions=[
                TriageSuggestion("fix_version", "CNV v4.22.0", "CNV v4.22.0", "GA target"),
            ],
            backport=BackportAnalysis(
                needs_backport=True,
                recommendations=[
                    BackportRecommendation("4.21", "release-4.21", "must", "Active"),
                ],
                overall_reasoning="Need backport",
            ),
        )
        text = build_comment_text(result)
        assert "CNV v4.22.0 (suggested)" in text
