"""Build and post structured triage comments on Jira bugs."""

from __future__ import annotations

import logging
from typing import Any

from jira import JIRA

from cnv_bug_triage.jira.client import days_since_last_agent_comment, post_comment
from cnv_bug_triage.schemas.config import AppConfig
from cnv_bug_triage.triage.checker import TriageResult

logger = logging.getLogger(__name__)


def build_comment_text(result: TriageResult, run_id: str = "") -> str:
    prefix = "[Bug Triage Agent]"
    run_part = f" (run {run_id})" if run_id else ""
    lines: list[str] = [f"{prefix} Triage analysis{run_part}", ""]

    missing = result.missing_fields
    if missing:
        lines.append("This bug is missing the following triage fields:")
        lines.append("")

        for check in result.checks:
            if check.is_ok:
                continue
            suggestion = result.suggestion_for(check.field_name)
            field_label = _field_display_name(check.field_name)
            lines.append(f"▸ *{field_label}* (currently: {check.current_value})")
            if suggestion:
                lines.append(f"  Suggestion: *{suggestion.suggested_display}*")
                lines.append(f'  Reasoning: "{suggestion.reasoning}"')
            else:
                lines.append("  _(no suggestion available)_")
            lines.append("")

    backport = result.backport
    if backport and (backport.needs_backport or backport.recommendations):
        fix_ver = ", ".join(result.bug.fix_versions) or "(none)"
        fv_suggestion = result.suggestion_for("fix_version")
        if fv_suggestion and not result.bug.fix_versions:
            fix_ver = f"{fv_suggestion.suggested_display} (suggested)"
        lines.append(f"▸ *Backport assessment*:")
        lines.append(f"  The fix targets: {fix_ver}. Backport recommended:")
        for rec in backport.recommendations:
            urgency_label = rec.urgency.upper().replace("_", " ")
            lines.append(
                f"  • {rec.version} ({rec.branch}) — "
                f"{urgency_label}: \"{rec.reasoning}\""
            )
        if backport.overall_reasoning:
            lines.append(f'  Overall: "{backport.overall_reasoning}"')
        lines.append("")

    if result.duplicates:
        lines.append("⚠ *Potential duplicates*:")
        for dup in result.duplicates:
            pct = int(dup.confidence * 100)
            lines.append(
                f"  • {dup.candidate_key} ({pct}%) — "
                f'"{dup.reasoning}"'
            )
        lines.append("")

    lines.append("---")
    run_tag = f" | run: {run_id}" if run_id else ""
    lines.append(f"_Generated by cnv-bug-triage{run_tag}_")

    return "\n".join(lines)


def should_post_comment(
    result: TriageResult,
    client: JIRA,
    cfg: AppConfig,
) -> tuple[bool, str]:
    has_missing = bool(result.missing_fields)
    has_backport = bool(
        result.backport
        and result.backport.needs_backport
    )
    has_duplicates = bool(result.duplicates)

    if not (has_missing or has_backport or has_duplicates):
        return False, "fully triaged, no backport/duplicates"

    days = days_since_last_agent_comment(
        client, result.bug.key, cfg.triage.comment_prefix,
    )
    if days is not None and days < cfg.triage.comment_cooldown_days:
        return False, f"cooldown ({days:.1f}d < {cfg.triage.comment_cooldown_days}d)"

    return True, ""


def post_triage_comment(
    result: TriageResult,
    client: JIRA,
    cfg: AppConfig,
    run_id: str = "",
) -> tuple[bool, str]:
    """Post a triage comment if appropriate.

    Returns (posted: bool, reason: str).
    """
    ok, reason = should_post_comment(result, client, cfg)
    if not ok:
        return False, reason

    text = build_comment_text(result, run_id=run_id)
    try:
        post_comment(client, result.bug.key, text)
        return True, "posted"
    except Exception as exc:
        logger.error(
            "Failed to post comment on %s: %s",
            result.bug.key, exc, exc_info=True,
        )
        return False, f"error: {exc}"


_FIELD_NAMES = {
    "assignee": "Assignee",
    "qa_contact": "QA Contact",
    "sprint": "Sprint",
    "priority": "Priority",
    "fix_version": "Fix Version",
}


def _field_display_name(field_name: str) -> str:
    return _FIELD_NAMES.get(field_name, field_name)
